// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using maple_web_api_async.Contexts;

namespace maple_web_api_async.Migrations
{
    [DbContext(typeof(BookContext))]
    [Migration("20200622061756_Initial DB Setup")]
    partial class InitialDBSetup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("maple_web_api_async.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("17b04541-76e3-4719-bcd5-bb2018918ec0"),
                            FirstName = "Siddharth",
                            LastName = "Seth"
                        },
                        new
                        {
                            Id = new Guid("4183f7f6-d017-4f64-aae2-695eaa6c65ee"),
                            FirstName = "Apoorva",
                            LastName = "Seth"
                        },
                        new
                        {
                            Id = new Guid("e735dd4d-bd83-484b-b166-61bf6e7c0803"),
                            FirstName = "Ankit",
                            LastName = "Jain"
                        });
                });

            modelBuilder.Entity("maple_web_api_async.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25efcf58-ec53-45e0-a879-ae1a1adfd340"),
                            AuthorId = new Guid("17b04541-76e3-4719-bcd5-bb2018918ec0"),
                            Description = "Tale of a lonely Dove in a harsh world",
                            Title = "A Dove's Tale"
                        },
                        new
                        {
                            Id = new Guid("357e1727-b7e0-4961-a072-8d999d328d88"),
                            AuthorId = new Guid("4183f7f6-d017-4f64-aae2-695eaa6c65ee"),
                            Description = "Story of rise and fall of a Hacker",
                            Title = "The Hacker"
                        },
                        new
                        {
                            Id = new Guid("1fe62c81-5e7a-4c81-bde0-a7b645edca6b"),
                            AuthorId = new Guid("e735dd4d-bd83-484b-b166-61bf6e7c0803"),
                            Description = "Tragedy in the personal life of a successful Business Tycoon",
                            Title = "The Business Man"
                        });
                });

            modelBuilder.Entity("maple_web_api_async.Entities.Book", b =>
                {
                    b.HasOne("maple_web_api_async.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
